# Generated by Django 6.0.4 on 2026-04-27 07:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GamePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('outdoor', '🏏 Outdoor / Ground'), ('online', '🎮 Online / Game')], max_length=10)),
                ('sport', models.CharField(choices=[('cricket', '🏏 Cricket'), ('football', '⚽ Football'), ('basketball', '🏀 Basketball'), ('volleyball', '🏐 Volleyball'), ('badminton', '🏸 Badminton'), ('kabaddi', '🤼 Kabaddi'), ('bgmi', '🔫 BGMI'), ('valorant', '🎯 Valorant'), ('fifa', '⚽ FIFA'), ('chess', '♟️ Chess'), ('ludo', '🎲 Ludo'), ('other', '🎮 Other')], max_length=20)),
                ('title', models.CharField(help_text='e.g. Need 4 players for cricket at Azad Maidan', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Any extra details')),
                ('players_have', models.PositiveIntegerField(default=1)),
                ('players_needed', models.PositiveIntegerField(default=1)),
                ('skill_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('pro', 'Pro')], default='beginner', max_length=15)),
                ('location', models.CharField(blank=True, help_text='Ground/venue name', max_length=200)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('play_date', models.DateField(blank=True, null=True)),
                ('play_time', models.TimeField(blank=True, null=True)),
                ('game_platform', models.CharField(blank=True, help_text='e.g. Mobile, PC, PS5', max_length=50)),
                ('game_id', models.CharField(blank=True, help_text='Your in-game ID/username', max_length=100)),
                ('status', models.CharField(choices=[('open', 'Open'), ('full', 'Full'), ('closed', 'Closed')], default='open', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('game_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='games.gamepost')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('area', models.CharField(blank=True, help_text='Locality/Area e.g. Andheri, Bandra', max_length=100)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('reputation', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, help_text='Why do you want to join?')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='games.gamepost')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('game_post', 'player')},
            },
        ),
    ]
