# Generated by Django 6.0.4 on 2026-04-28 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_reputation'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamepost',
            name='map_link',
            field=models.URLField(blank=True, help_text='Paste Google Maps link of the ground'),
        ),
    ]
