# Generated by Django 6.0.4 on 2026-04-29 06:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_gamepost_map_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('venue_type', models.CharField(choices=[('ground', '🏏 Ground'), ('turf', '⚽ Turf')], max_length=10)),
                ('area', models.CharField(help_text='e.g. Vile Parle', max_length=100)),
                ('city', models.CharField(help_text='e.g. Mumbai', max_length=100)),
                ('address', models.TextField(blank=True)),
                ('map_link', models.URLField(blank=True)),
                ('sports', models.CharField(choices=[('cricket', '🏏 Cricket'), ('football', '⚽ Football'), ('basketball', '🏀 Basketball'), ('volleyball', '🏐 Volleyball'), ('badminton', '🏸 Badminton'), ('kabaddi', '🤼 Kabaddi'), ('multiple', '🎯 Multiple Sports')], default='multiple', max_length=20)),
                ('contact', models.CharField(blank=True, max_length=15)),
                ('opening_hours', models.CharField(blank=True, help_text='e.g. 6am - 10pm', max_length=100)),
                ('entry_fee', models.CharField(blank=True, help_text='e.g. Free, Rs 50/person', max_length=100)),
                ('price_per_hour', models.CharField(blank=True, help_text='e.g. Rs 800/hr (for turfs)', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='venues/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='venues/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='venues/')),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='venues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['city', 'area', 'name'],
            },
        ),
    ]
