# Generated by Django 6.0.4 on 2026-05-19 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_venue_latitude_venue_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamepost',
            name='whatsapp_link',
            field=models.URLField(blank=True, help_text='Paste WhatsApp group invite link'),
        ),
    ]
